# Generated by Django 3.2.23 on 2023-12-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0116_auto_20231204_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='QpsTimeseriesProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qps_timeseries_projects', to='qdjango.project')),
            ],
            options={
                'verbose_name': 'Qps Timeseries Project',
            },
        ),
        migrations.CreateModel(
            name='QpsTimeseriesLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_date', models.DateField(verbose_name='Min date')),
                ('max_date', models.DateField(verbose_name='Max date')),
                ('min_y', models.FloatField(verbose_name='Min Y')),
                ('max_y', models.FloatField(verbose_name='Max Y')),
                ('replica_up', models.BooleanField(default=False, verbose_name='Replica update')),
                ('replica_down', models.BooleanField(default=False, verbose_name='Replica down')),
                ('replica_dist', models.FloatField(default=0.0, verbose_name='Replica distance')),
                ('h_grid', models.BooleanField(default=False, verbose_name='Horizontal grid')),
                ('v_grid', models.BooleanField(default=False, verbose_name='Vertical grid')),
                ('lines', models.BooleanField(default=False, verbose_name='Lines')),
                ('labels', models.BooleanField(default=True, verbose_name='Labels')),
                ('lin_trend', models.BooleanField(default=False, verbose_name='Lin trend')),
                ('poly_trend', models.BooleanField(default=False, verbose_name='Poly trend')),
                ('detrending', models.BooleanField(default=False, verbose_name='Detrending')),
                ('x_axis_label', models.CharField(max_length=255, verbose_name='X axis label')),
                ('y_axis_label', models.CharField(max_length=255, verbose_name='Y axis label')),
                ('title_part_1', models.CharField(max_length=255, verbose_name='Title part 1')),
                ('title_part_1_field', models.CharField(choices=[], max_length=255, verbose_name='Title part 1 field')),
                ('title_part_2', models.CharField(max_length=255, verbose_name='Title part 2')),
                ('title_part_2_field', models.CharField(choices=[], max_length=255, verbose_name='Title part 2 field')),
                ('title_part_3', models.CharField(max_length=255, verbose_name='Title part 3')),
                ('title_part_3_field', models.CharField(choices=[], max_length=255, verbose_name='Title part 3 field')),
                ('layer', models.ForeignKey(help_text='Select vector project layers to use for reporting: only follow geometry types are allowed: Point, MultiPoint, Point25D, MultiPointZ, PointZ, Polygon, MultiPolygon, Polygon25D, PolygonZ, MultiPolygonZ, LineString, MultiLineStringLineString25D, LineStringZ, MultiLineStringZ', on_delete=django.db.models.deletion.CASCADE, to='qdjango.layer')),
                ('qps_timeseries_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qps_timeseries.qpstimeseriesproject')),
            ],
            options={
                'verbose_name': 'Qps Timeseries Layer',
            },
        ),
    ]
