# Generated by Django 3.2.23 on 2023-12-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0116_auto_20231204_1357'),
        ('qps_timeseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='layer',
            field=models.ForeignKey(help_text='Select vector project layers to use for PS Timeseries: only follow geometry types are allowed: Point, MultiPoint, Point25D, MultiPointZ, PointZ, Polygon, MultiPolygon, Polygon25D, PolygonZ, MultiPolygonZ, LineString, MultiLineStringLineString25D, LineStringZ, MultiLineStringZ', on_delete=django.db.models.deletion.CASCADE, to='qdjango.layer'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='replica_dist',
            field=models.FloatField(default=0.0, verbose_name='Distance [mm]'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='replica_down',
            field=models.BooleanField(default=False, verbose_name='Down'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='replica_up',
            field=models.BooleanField(default=False, verbose_name='Up'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='title_part_1',
            field=models.CharField(default='coher.:', max_length=255, verbose_name='Title part 1'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='title_part_2',
            field=models.CharField(default='vel..:', max_length=255, verbose_name='Title part 2'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='title_part_3',
            field=models.CharField(default='v_stdev.:', max_length=255, verbose_name='Title part 3'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='x_axis_label',
            field=models.CharField(default='[Date]', max_length=255, verbose_name='X axis label'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='y_axis_label',
            field=models.CharField(default='[mm]', max_length=255, verbose_name='Y axis label'),
        ),
    ]
