# Generated by Django 3.2.23 on 2023-12-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qps_timeseries', '0002_auto_20231213_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpstimeserieslayer',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='title_part_1_field',
            field=models.CharField(max_length=255, verbose_name='Title part 1 field'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='title_part_2_field',
            field=models.CharField(max_length=255, verbose_name='Title part 2 field'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='title_part_3_field',
            field=models.CharField(max_length=255, verbose_name='Title part 3 field'),
        ),
    ]
