# Generated by Django 3.2.23 on 2023-12-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qps_timeseries', '0003_auto_20231214_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='qps_timeseries_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qps_timeseries.qpstimeseriesproject', unique=True),
        ),
    ]
