# Generated by Django 3.2.23 on 2023-12-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qps_timeseries', '0004_alter_qpstimeserieslayer_qps_timeseries_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='title_part_2',
            field=models.CharField(default='vel.:', max_length=255, verbose_name='Title part 2'),
        ),
    ]
