# Generated by Django 3.2.23 on 2023-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qps_timeseries', '0005_alter_qpstimeserieslayer_title_part_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='max_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Y'),
        ),
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='min_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Min Y'),
        ),
    ]
