# Generated by Django 3.2.23 on 2024-01-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qps_timeseries', '0006_auto_20231228_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpstimeserieslayer',
            name='std',
            field=models.BooleanField(default=False, verbose_name='Standard Deviation'),
        ),
    ]
