# Generated by Django 3.2.23 on 2024-01-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qps_timeseries', '0007_qpstimeserieslayer_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpstimeserieslayer',
            name='qps_timeseries_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qps_timeseries.qpstimeseriesproject'),
        ),
    ]
